#https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#appendix.application-properties
spring:
  datasource:
    url: "jdbc:h2:mem:test"
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

server:
  port: 3000